import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled, { ThemeProvider } from 'styled-components'
import {theme} from '../assets/theme';
import GlobalStyles from '../assets/GlobalStyles';
import Header from '../components/Header/Header';
import Main from '../components/Main/Main';
import New from '../components/atoms/New/New';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ThemeProvider theme={theme}>

       <GlobalStyles /> 
       <Header />
        <Main />
        
      </ThemeProvider>

    </div>
  )
}

export default Home
